export const sizesAllowed = [
	"ÚNICO",
	"PP",
	"P",
	"M",
	"G",
	"GG",
	"XG",
	"XGG",
	"EG",
	"EGG",
	"0",
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"10",
	"11",
	"12",
	"13",
	"14",
	"15",
	"16",
	"17",
	"18",
	"19",
	"20",
	"21",
	"22",
	"23",
	"24",
	"25",
	"26",
	"27",
	"28",
	"29",
	"30",
	"31",
	"32",
	"33",
	"34",
	"35",
	"36",
	"37",
	"38",
	"39",
	"40",
	"41",
	"42",
	"43",
	"44",
	"45",
	"46",
	"47",
	"48",
	"49",
	"50",
	"51",
	"52",
	"53",
	"54",
	"55",
	"56",
	"57",
	"58",
	"59",
	"60",
	"61",
	"62",
	"63",
	"64",
	"65",
	"66",
	"67",
	"68",
	"69",
	"70",
	"71",
	"72",
	"73",
	"74",
	"75",
	"76",
	"77",
	"78",
	"79",
	"80",
	"81",
	"82",
	"83",
	"84",
	"85",
	"86",
	"87",
	"88",
	"89",
	"90",
	"91",
	"92",
	"93",
	"94",
	"95",
	"96",
	"97",
	"98",
	"99",
	"100",
];

export const categoryAllowed = [
	"blusa",
	"conjunto",
	"cropped",
	"jeans",
	"macacão",
	"short",
	"vestido",
	"calça",
];

export const colors = {
	marrom: { colorCode: "#800000", color: "maroon", colorDisplay: "marrom" },
	vermelhoescuro: {
		colorCode: "#8B0000",
		color: "darkred",
		colorDisplay: "vermelho escuro",
	},
	castanho: { colorCode: "#A52A2A", color: "brown", colorDisplay: "castanho" },
	tijolorefratário: {
		colorCode: "#B22222",
		color: "firebrick",
		colorDisplay: "tijolo refratário",
	},
	carmesim: {
		colorCode: "#DC143C",
		color: "crimson",
		colorDisplay: "carmesim",
	},
	vermelho: { colorCode: "#FF0000", color: "red", colorDisplay: "vermelho" },
	tomate: { colorCode: "#FF6347", color: "tomato", colorDisplay: "tomate" },
	coral: { colorCode: "#FF7F50", color: "coral", colorDisplay: "coral" },
	vermelhoindiano: {
		colorCode: "#CD5C5C",
		color: "indianred",
		colorDisplay: "vermelho indiano",
	},
	coralclaro: {
		colorCode: "#F08080",
		color: "lightcoral",
		colorDisplay: "coral claro",
	},
	salmãoescuro: {
		colorCode: "#E9967A",
		color: "darksalmon",
		colorDisplay: "salmão escuro",
	},
	salmão: { colorCode: "#FA8072", color: "salmon", colorDisplay: "salmão" },
	salmãoclaro: {
		colorCode: "#FFA07A",
		color: "lightsalmon",
		colorDisplay: "salmão claro",
	},
	vermelhoalaranjado: {
		colorCode: "#FF4500",
		color: "orangered",
		colorDisplay: "vermelho alaranjado",
	},
	laranjaescuro: {
		colorCode: "#FF8C00",
		color: "darkorange",
		colorDisplay: "laranja escuro",
	},
	laranja: { colorCode: "#FFA500", color: "orange", colorDisplay: "laranja" },
	ouro: { colorCode: "#FFD700", color: "gold", colorDisplay: "ouro" },
	hastedouradaescura: {
		colorCode: "#B8860B",
		color: "darkgoldenrod",
		colorDisplay: "haste dourada escura",
	},
	varadeouro: {
		colorCode: "#DAA520",
		color: "goldenrod",
		colorDisplay: "vara de ouro",
	},
	hastedouradapálida: {
		colorCode: "#EEE8AA",
		color: "palegoldenrod",
		colorDisplay: "haste dourada pálida",
	},
	cáquiescuro: {
		colorCode: "#BDB76B",
		color: "darkkhaki",
		colorDisplay: "cáqui escuro",
	},
	cáqui: { colorCode: "#F0E68C", color: "khaki", colorDisplay: "cáqui" },
	oliva: { colorCode: "#808000", color: "olive", colorDisplay: "oliva" },
	amarelo: { colorCode: "#FFFF00", color: "yellow", colorDisplay: "amarelo" },
	amarelverde: {
		colorCode: "#9ACD32",
		color: "yellowgreen",
		colorDisplay: "amarelo verde",
	},
	verdeolivaescuro: {
		colorCode: "#556B2F",
		color: "darkolivegreen",
		colorDisplay: "verde oliva escuro",
	},
	azeitonamonótona: {
		colorCode: "#6B8E23",
		color: "olivedrab",
		colorDisplay: "azeitona monótona",
	},
	gramadoverde: {
		colorCode: "#7CFC00",
		color: "lawngreen",
		colorDisplay: "gramado verde",
	},
	verdeamarelo: {
		colorCode: "#ADFF2F",
		color: "greenyellow",
		colorDisplay: "verde amarelo",
	},
	verdeescuro: {
		colorCode: "#006400",
		color: "darkgreen",
		colorDisplay: "verde escuro",
	},
	verde: { colorCode: "#008000", color: "green", colorDisplay: "verde" },
	verdefloresta: {
		colorCode: "#228B22",
		color: "forestgreen",
		colorDisplay: "verde floresta",
	},
	lima: { colorCode: "#00FF00", color: "lime", colorDisplay: "lima" },
	verdelimão: {
		colorCode: "#32CD32",
		color: "limegreen",
		colorDisplay: "verde limão",
	},
	luzverde: {
		colorCode: "#90EE90",
		color: "lightgreen",
		colorDisplay: "luz verde",
	},
	verdepálido: {
		colorCode: "#98FB98",
		color: "palegreen",
		colorDisplay: "verde pálido",
	},
	verdemarescuro: {
		colorCode: "#8FBC8F",
		color: "darkseagreen",
		colorDisplay: "verde mar escuro",
	},
	verdeprimaveramédio: {
		colorCode: "#00FA9A",
		color: "mediumspringgreen",
		colorDisplay: "verde primavera médio",
	},
	primaveraverde: {
		colorCode: "#00FF7F",
		color: "springgreen",
		colorDisplay: "primavera verde",
	},
	verdemar: {
		colorCode: "#2E8B57",
		color: "seagreen",
		colorDisplay: "verde mar",
	},
	aquamarinhomédio: {
		colorCode: "#66CDAA",
		color: "mediumaquamarine",
		colorDisplay: "aqua marinho médio",
	},
	verdemarmédio: {
		colorCode: "#3CB371",
		color: "mediumseagreen",
		colorDisplay: "verde mar médio",
	},
	verdemarclaro: {
		colorCode: "#20B2AA",
		color: "lightseagreen",
		colorDisplay: "verde mar claro",
	},
	cinzaardósiaescuro: {
		colorCode: "#2F4F4F",
		color: "darkslategray",
		colorDisplay: "cinza ardósia escuro",
	},
	cerceta: { colorCode: "#008080", color: "teal", colorDisplay: "cerceta" },
	cianoescuro: {
		colorCode: "#008B8B",
		color: "darkcyan",
		colorDisplay: "ciano escuro",
	},
	aqua: { colorCode: "#00FFFF", color: "aqua", colorDisplay: "aqua" },
	ciano: { colorCode: "#00FFFF", color: "cyan", colorDisplay: "ciano" },
	cianoclaro: {
		colorCode: "#E0FFFF",
		color: "lightcyan",
		colorDisplay: "ciano claro",
	},
	turquesaescuro: {
		colorCode: "#00CED1",
		color: "darkturquoise",
		colorDisplay: "turquesa escuro",
	},
	turquesa: {
		colorCode: "#40E0D0",
		color: "turquoise",
		colorDisplay: "turquesa",
	},
	turquesamédio: {
		colorCode: "#48D1CC",
		color: "mediumturquoise",
		colorDisplay: "turquesa médio",
	},
	turquesapálida: {
		colorCode: "#AFEEEE",
		color: "paleturquoise",
		colorDisplay: "turquesa pálida",
	},
	verdeágua: {
		colorCode: "#7FFFD4",
		color: "aquamarine",
		colorDisplay: "verde água",
	},
	póazul: {
		colorCode: "#B0E0E6",
		color: "powderblue",
		colorDisplay: "pó azul",
	},
	azulbebê: {
		colorCode: "#add8e6",
		color: "babyblue",
		colorDisplay: "azul bebê",
	},
	azulcadete: {
		colorCode: "#5F9EA0",
		color: "cadetblue",
		colorDisplay: "azul cadete",
	},
	açoazul: {
		colorCode: "#4682B4",
		color: "steelblue",
		colorDisplay: "aço azul",
	},
	flordemilhoazul: {
		colorCode: "#6495ED",
		color: "cornflowerblue",
		colorDisplay: "flor de milho azul",
	},
	céuazulprofundo: {
		colorCode: "#00BFFF",
		color: "deepskyblue",
		colorDisplay: "céu azul profundo",
	},
	trapaceiroazul: {
		colorCode: "#1E90FF",
		color: "dodgerblue",
		colorDisplay: "trapaceiro azul",
	},
	azulclaro: {
		colorCode: "#ADD8E6",
		color: "lightblue",
		colorDisplay: "azul claro",
	},
	céuazul: { colorCode: "#87CEEB", color: "skyblue", colorDisplay: "céu azul" },
	céuazulclaro: {
		colorCode: "#87CEFA",
		color: "lightskyblue",
		colorDisplay: "céu azul claro",
	},
	azuldameianoite: {
		colorCode: "#191970",
		color: "midnightblue",
		colorDisplay: "azul da meia noite",
	},
	marinha: { colorCode: "#000080", color: "navy", colorDisplay: "marinha" },
	azulescuro: {
		colorCode: "#00008B",
		color: "darkblue",
		colorDisplay: "azul escuro",
	},
	azulmédio: {
		colorCode: "#0000CD",
		color: "mediumblue",
		colorDisplay: "azul médio",
	},
	azul: { colorCode: "#0000FF", color: "blue", colorDisplay: "azul" },
	azulroyal: {
		colorCode: "#4169E1",
		color: "royalblue",
		colorDisplay: "azul royal",
	},
	violetaazul: {
		colorCode: "#8A2BE2",
		color: "blueviolet",
		colorDisplay: "violeta azul",
	},
	índigo: { colorCode: "#4B0082", color: "indigo", colorDisplay: "índigo" },
	azulardósiaescuro: {
		colorCode: "#483D8B",
		color: "darkslateblue",
		colorDisplay: "azul ardósia escuro",
	},
	azulardósia: {
		colorCode: "#6A5ACD",
		color: "slateblue",
		colorDisplay: "azul ardósia",
	},
	azulardósiamédio: {
		colorCode: "#7B68EE",
		color: "mediumslateblue",
		colorDisplay: "azul ardósia médio",
	},
	roxomédio: {
		colorCode: "#9370DB",
		color: "mediumpurple",
		colorDisplay: "roxo médio",
	},
	magentaescuro: {
		colorCode: "#8B008B",
		color: "darkmagenta",
		colorDisplay: "magenta escuro",
	},
	violetaescuro: {
		colorCode: "#9400D3",
		color: "darkviolet",
		colorDisplay: "violeta escuro",
	},
	orquídeaescura: {
		colorCode: "#9932CC",
		color: "darkorchid",
		colorDisplay: "orquídea escura",
	},
	orquídeamédia: {
		colorCode: "#BA55D3",
		color: "mediumorchid",
		colorDisplay: "orquídea média",
	},
	roxo: { colorCode: "#800080", color: "purple", colorDisplay: "roxo" },
	cardo: { colorCode: "#D8BFD8", color: "thistle", colorDisplay: "cardo" },
	ameixa: { colorCode: "#DDA0DD", color: "plum", colorDisplay: "ameixa" },
	tolet: { colorCode: "#EE82EE", color: "violet", colorDisplay: "tolet" },
	magenta: { colorCode: "#FF00FF", color: "magenta", colorDisplay: "magenta" },
	orquídea: { colorCode: "#DA70D6", color: "orchid", colorDisplay: "orquídea" },
	vermelhovioletamédio: {
		colorCode: "#C71585",
		color: "mediumvioletred",
		colorDisplay: "vermelho violeta médio",
	},
	vermelhovioletapálido: {
		colorCode: "#DB7093",
		color: "palevioletred",
		colorDisplay: "vermelho violeta pálido",
	},
	rosapink: {
		colorCode: "#FF1493",
		color: "deeppink",
		colorDisplay: "rosa pink",
	},
	rosaquente: {
		colorCode: "#FF69B4",
		color: "hotpink",
		colorDisplay: "rosa quente",
	},
	luzrosa: {
		colorCode: "#FFB6C1",
		color: "lightpink",
		colorDisplay: "luz rosa",
	},
	rosa: { colorCode: "#FFC0CB", color: "pink", colorDisplay: "rosa" },
	brancoantigo: {
		colorCode: "#FAEBD7",
		color: "antiquewhite",
		colorDisplay: "branco antigo",
	},
	bege: { colorCode: "#F5F5DC", color: "beige", colorDisplay: "bege" },
	bisque: { colorCode: "#FFE4C4", color: "bisque", colorDisplay: "bisque" },
	amêndoabranqueada: {
		colorCode: "#FFEBCD",
		color: "blanchedalmond",
		colorDisplay: "amêndoa branqueada",
	},
	trigo: { colorCode: "#F5DEB3", color: "wheat", colorDisplay: "trigo" },
	sedademilho: {
		colorCode: "#FFF8DC",
		color: "cornsilk",
		colorDisplay: "seda de milho",
	},
	chiffondelimão: {
		colorCode: "#FFFACD",
		color: "lemonchiffon",
		colorDisplay: "chiffon de limão",
	},
	hastedouradaclaraamarela: {
		colorCode: "#FAFAD2",
		color: "lightgoldenrodyellow",
		colorDisplay: "haste dourada clara amarela",
	},
	luzamarela: {
		colorCode: "#FFFFE0",
		color: "lightyellow",
		colorDisplay: "luz amarela",
	},
	selamarrom: {
		colorCode: "#8B4513",
		color: "saddlebrown",
		colorDisplay: "sela marrom",
	},
	siena: { colorCode: "#A0522D", color: "sienna", colorDisplay: "siena" },
	chocolate: {
		colorCode: "#D2691E",
		color: "chocolate",
		colorDisplay: "chocolate",
	},
	peru: { colorCode: "#CD853F", color: "peru", colorDisplay: "peru" },
	marromarenoso: {
		colorCode: "#F4A460",
		color: "sandybrown",
		colorDisplay: "marrom arenoso",
	},
	madeirarobusta: {
		colorCode: "#DEB887",
		color: "burlywood",
		colorDisplay: "madeira robusta",
	},
	bronzeado: { colorCode: "#D2B48C", color: "tan", colorDisplay: "bronzeado" },
	marromrosado: {
		colorCode: "#BC8F8F",
		color: "rosybrown",
		colorDisplay: "marrom rosado",
	},
	mocassim: {
		colorCode: "#FFE4B5",
		color: "moccasin",
		colorDisplay: "mocassim",
	},
	navajobranco: {
		colorCode: "#FFDEAD",
		color: "navajowhite",
		colorDisplay: "navajo branco",
	},
	folhadodepêssego: {
		colorCode: "#FFDAB9",
		color: "peachpuff",
		colorDisplay: "folhado de pêssego",
	},
	rosaenevoada: {
		colorCode: "#FFE4E1",
		color: "mistyrose",
		colorDisplay: "rosa enevoada",
	},
	rubordelavanda: {
		colorCode: "#FFF0F5",
		color: "lavenderblush",
		colorDisplay: "rubor de lavanda",
	},
	linho: { colorCode: "#FAF0E6", color: "linen", colorDisplay: "linho" },
	rendavelha: {
		colorCode: "#FDF5E6",
		color: "oldlace",
		colorDisplay: "renda velha",
	},
	chicotedepapaia: {
		colorCode: "#FFEFD5",
		color: "papayawhip",
		colorDisplay: "chicote de papaia",
	},
	conchadomar: {
		colorCode: "#FFF5EE",
		color: "seashell",
		colorDisplay: "concha do mar",
	},
	cremedementa: {
		colorCode: "#F5FFFA",
		color: "mintcream",
		colorDisplay: "creme de menta",
	},
	ardósiacinza: {
		colorCode: "#708090",
		color: "slategray",
		colorDisplay: "ardósia cinza",
	},
	cinzaardósiaclaro: {
		colorCode: "#778899",
		color: "lightslategray",
		colorDisplay: "cinza ardósia claro",
	},
	azulaçoclaro: {
		colorCode: "#B0C4DE",
		color: "lightsteelblue",
		colorDisplay: "azul aço claro",
	},
	lavanda: { colorCode: "#E6E6FA", color: "lavender", colorDisplay: "lavanda" },
	floralbranco: {
		colorCode: "#FFFAF0",
		color: "floralwhite",
		colorDisplay: "floral branco",
	},
	aliceazul: {
		colorCode: "#F0F8FF",
		color: "aliceblue",
		colorDisplay: "alice azul",
	},
	fantasmabranco: {
		colorCode: "#F8F8FF",
		color: "ghostwhite",
		colorDisplay: "fantasma branco",
	},
	melada: { colorCode: "#F0FFF0", color: "honeydew", colorDisplay: "melada" },
	marfim: { colorCode: "#FFFFF0", color: "ivory", colorDisplay: "marfim" },
	azulceleste: {
		colorCode: "#F0FFFF",
		color: "azure",
		colorDisplay: "azul celeste",
	},
	neve: { colorCode: "#FFFAFA", color: "snow", colorDisplay: "neve" },
	preto: { colorCode: "#000000", color: "black", colorDisplay: "preto" },
	cinzaescuro: {
		colorCode: "#696969",
		color: "dimgray",
		colorDisplay: "cinza escuro",
	},
	cinza: { colorCode: "#808080", color: "gray", colorDisplay: "cinza" },
	cinzaescuromédio: {
		colorCode: "#A9A9A9",
		color: "darkgray",
		colorDisplay: "cinza escuro médio",
	},
	prata: { colorCode: "#C0C0C0", color: "silver", colorDisplay: "prata" },
	cinzaclaro: {
		colorCode: "#D3D3D3",
		color: "lightgray",
		colorDisplay: "cinza claro",
	},
	ganhosboro: {
		colorCode: "#DCDCDC",
		color: "gainsboro",
		colorDisplay: "ganhosboro",
	},
	fumaçabranca: {
		colorCode: "#F5F5F5",
		color: "whitesmoke",
		colorDisplay: "fumaça branca",
	},
	branco: { colorCode: "#FFFFFF", color: "white", colorDisplay: "branco" },
	marsala: { colorCode: "#B57170", color: "marsala", colorDisplay: "marsala" },
	lilás: { colorCode: "#c8a2c8", color: "lilac", colorDisplay: "lilás" },
	rosabebê: {
		colorCode: "#FFB6C1",
		color: "lighpink",
		colorDisplay: "rosa bebê",
	},
};

// TABLE WITH ENGLISH COLORS
/* export const colors = {
	maroon: { colorCode: "#800000", color: "maroon", colorDisplay: "Marrom" },
	darkred: {
		colorCode: "#8B0000",
		color: "darkred",
		colorDisplay: "Vermelho Escuro",
	},
	brown: { colorCode: "#A52A2A", color: "brown", colorDisplay: "Castanho" },
	firebrick: {
		colorCode: "#B22222",
		color: "firebrick",
		colorDisplay: "Tijolo Refratário",
	},
	crimson: { colorCode: "#DC143C", color: "crimson", colorDisplay: "Carmesim" },
	red: { colorCode: "#FF0000", color: "red", colorDisplay: "Vermelho" },
	tomato: { colorCode: "#FF6347", color: "tomato", colorDisplay: "Tomate" },
	coral: { colorCode: "#FF7F50", color: "coral", colorDisplay: "Coral" },
	indianred: {
		colorCode: "#CD5C5C",
		color: "indianred",
		colorDisplay: "Vermelho Indiano",
	},
	lightcoral: {
		colorCode: "#F08080",
		color: "lightcoral",
		colorDisplay: "Coral Claro",
	},
	darksalmon: {
		colorCode: "#E9967A",
		color: "darksalmon",
		colorDisplay: "Salmão Escuro",
	},
	salmon: { colorCode: "#FA8072", color: "salmon", colorDisplay: "Salmão" },
	lightsalmon: {
		colorCode: "#FFA07A",
		color: "lightsalmon",
		colorDisplay: "Salmão Claro",
	},
	orangered: {
		colorCode: "#FF4500",
		color: "orangered",
		colorDisplay: "Vermelho Alaranjado",
	},
	darkorange: {
		colorCode: "#FF8C00",
		color: "darkorange",
		colorDisplay: "Laranja Escuro",
	},
	orange: { colorCode: "#FFA500", color: "orange", colorDisplay: "Laranja" },
	gold: { colorCode: "#FFD700", color: "gold", colorDisplay: "Ouro" },
	darkgoldenrod: {
		colorCode: "#B8860B",
		color: "darkgoldenrod",
		colorDisplay: "Haste Dourada Escura",
	},
	goldenrod: {
		colorCode: "#DAA520",
		color: "goldenrod",
		colorDisplay: "Vara De Ouro",
	},
	palegoldenrod: {
		colorCode: "#EEE8AA",
		color: "palegoldenrod",
		colorDisplay: "Haste Dourada Pálida",
	},
	darkkhaki: {
		colorCode: "#BDB76B",
		color: "darkkhaki",
		colorDisplay: "Cáqui Escuro",
	},
	khaki: { colorCode: "#F0E68C", color: "khaki", colorDisplay: "Cáqui" },
	olive: { colorCode: "#808000", color: "olive", colorDisplay: "Oliva" },
	yellow: { colorCode: "#FFFF00", color: "yellow", colorDisplay: "Amarelo" },
	yellowgreen: {
		colorCode: "#9ACD32",
		color: "yellowgreen",
		colorDisplay: "Amarelo Verde",
	},
	darkolivegreen: {
		colorCode: "#556B2F",
		color: "darkolivegreen",
		colorDisplay: "Verde Oliva Escuro",
	},
	olivedrab: {
		colorCode: "#6B8E23",
		color: "olivedrab",
		colorDisplay: "Azeitona Monótona",
	},
	lawngreen: {
		colorCode: "#7CFC00",
		color: "lawngreen",
		colorDisplay: "Gramado Verde",
	},
	greenyellow: {
		colorCode: "#ADFF2F",
		color: "greenyellow",
		colorDisplay: "Verde Amarelo",
	},
	darkgreen: {
		colorCode: "#006400",
		color: "darkgreen",
		colorDisplay: "Verde Escuro",
	},
	green: { colorCode: "#008000", color: "green", colorDisplay: "Verde" },
	forestgreen: {
		colorCode: "#228B22",
		color: "forestgreen",
		colorDisplay: "Verde Floresta",
	},
	lime: { colorCode: "#00FF00", color: "lime", colorDisplay: "Lima" },
	limegreen: {
		colorCode: "#32CD32",
		color: "limegreen",
		colorDisplay: "Verde Limão",
	},
	lightgreen: {
		colorCode: "#90EE90",
		color: "lightgreen",
		colorDisplay: "Luz Verde",
	},
	palegreen: {
		colorCode: "#98FB98",
		color: "palegreen",
		colorDisplay: "Verde Pálido",
	},
	darkseagreen: {
		colorCode: "#8FBC8F",
		color: "darkseagreen",
		colorDisplay: "Verde Mar Escuro",
	},
	mediumspringgreen: {
		colorCode: "#00FA9A",
		color: "mediumspringgreen",
		colorDisplay: "Verde Primavera Médio",
	},
	springgreen: {
		colorCode: "#00FF7F",
		color: "springgreen",
		colorDisplay: "Primavera Verde",
	},
	seagreen: {
		colorCode: "#2E8B57",
		color: "seagreen",
		colorDisplay: "Verde Mar",
	},
	mediumaquamarine: {
		colorCode: "#66CDAA",
		color: "mediumaquamarine",
		colorDisplay: "Aqua Marinho Médio",
	},
	mediumseagreen: {
		colorCode: "#3CB371",
		color: "mediumseagreen",
		colorDisplay: "Verde Mar Médio",
	},
	lightseagreen: {
		colorCode: "#20B2AA",
		color: "lightseagreen",
		colorDisplay: "Verde Mar Claro",
	},
	darkslategray: {
		colorCode: "#2F4F4F",
		color: "darkslategray",
		colorDisplay: "Cinza Ardósia Escuro",
	},
	teal: { colorCode: "#008080", color: "teal", colorDisplay: "Cerceta" },
	darkcyan: {
		colorCode: "#008B8B",
		color: "darkcyan",
		colorDisplay: "Ciano Escuro",
	},
	aqua: { colorCode: "#00FFFF", color: "aqua", colorDisplay: "Aqua" },
	cyan: { colorCode: "#00FFFF", color: "cyan", colorDisplay: "Ciano" },
	lightcyan: {
		colorCode: "#E0FFFF",
		color: "lightcyan",
		colorDisplay: "Ciano Claro",
	},
	darkturquoise: {
		colorCode: "#00CED1",
		color: "darkturquoise",
		colorDisplay: "Turquesa Escuro",
	},
	turquoise: {
		colorCode: "#40E0D0",
		color: "turquoise",
		colorDisplay: "Turquesa",
	},
	mediumturquoise: {
		colorCode: "#48D1CC",
		color: "mediumturquoise",
		colorDisplay: "Turquesa Médio",
	},
	paleturquoise: {
		colorCode: "#AFEEEE",
		color: "paleturquoise",
		colorDisplay: "Turquesa Pálida",
	},
	aquamarine: {
		colorCode: "#7FFFD4",
		color: "aquamarine",
		colorDisplay: "Verde Água",
	},
	powderblue: {
		colorCode: "#B0E0E6",
		color: "powderblue",
		colorDisplay: "Pó Azul",
	},
	babyblue: {
		colorCode: "#add8e6",
		color: "babyblue",
		colorDisplay: "Azul Bebê",
	},
	cadetblue: {
		colorCode: "#5F9EA0",
		color: "cadetblue",
		colorDisplay: "Azul Cadete",
	},
	steelblue: {
		colorCode: "#4682B4",
		color: "steelblue",
		colorDisplay: "Aço Azul",
	},
	cornflowerblue: {
		colorCode: "#6495ED",
		color: "cornflowerblue",
		colorDisplay: "Flor De Milho Azul",
	},
	deepskyblue: {
		colorCode: "#00BFFF",
		color: "deepskyblue",
		colorDisplay: "Céu Azul Profundo",
	},
	dodgerblue: {
		colorCode: "#1E90FF",
		color: "dodgerblue",
		colorDisplay: "Trapaceiro Azul",
	},
	lightblue: {
		colorCode: "#ADD8E6",
		color: "lightblue",
		colorDisplay: "Azul Claro",
	},
	skyblue: { colorCode: "#87CEEB", color: "skyblue", colorDisplay: "Céu Azul" },
	lightskyblue: {
		colorCode: "#87CEFA",
		color: "lightskyblue",
		colorDisplay: "Céu Azul Claro",
	},
	midnightblue: {
		colorCode: "#191970",
		color: "midnightblue",
		colorDisplay: "Azul Da Meia Noite",
	},
	navy: { colorCode: "#000080", color: "navy", colorDisplay: "Marinha" },
	darkblue: {
		colorCode: "#00008B",
		color: "darkblue",
		colorDisplay: "Azul Escuro",
	},
	mediumblue: {
		colorCode: "#0000CD",
		color: "mediumblue",
		colorDisplay: "Azul Médio",
	},
	blue: { colorCode: "#0000FF", color: "blue", colorDisplay: "Azul" },
	royalblue: {
		colorCode: "#4169E1",
		color: "royalblue",
		colorDisplay: "Azul Royal",
	},
	blueviolet: {
		colorCode: "#8A2BE2",
		color: "blueviolet",
		colorDisplay: "Violeta Azul",
	},
	indigo: { colorCode: "#4B0082", color: "indigo", colorDisplay: "Índigo" },
	darkslateblue: {
		colorCode: "#483D8B",
		color: "darkslateblue",
		colorDisplay: "Azul Ardósia Escuro",
	},
	slateblue: {
		colorCode: "#6A5ACD",
		color: "slateblue",
		colorDisplay: "Azul Ardósia",
	},
	mediumslateblue: {
		colorCode: "#7B68EE",
		color: "mediumslateblue",
		colorDisplay: "Azul Ardósia Médio",
	},
	mediumpurple: {
		colorCode: "#9370DB",
		color: "mediumpurple",
		colorDisplay: "Roxo Médio",
	},
	darkmagenta: {
		colorCode: "#8B008B",
		color: "darkmagenta",
		colorDisplay: "Magenta Escuro",
	},
	darkviolet: {
		colorCode: "#9400D3",
		color: "darkviolet",
		colorDisplay: "Violeta Escuro",
	},
	darkorchid: {
		colorCode: "#9932CC",
		color: "darkorchid",
		colorDisplay: "Orquídea Escura",
	},
	mediumorchid: {
		colorCode: "#BA55D3",
		color: "mediumorchid",
		colorDisplay: "Orquídea Média",
	},
	purple: { colorCode: "#800080", color: "purple", colorDisplay: "Roxo" },
	thistle: { colorCode: "#D8BFD8", color: "thistle", colorDisplay: "Cardo" },
	plum: { colorCode: "#DDA0DD", color: "plum", colorDisplay: "Ameixa" },
	violet: { colorCode: "#EE82EE", color: "violet", colorDisplay: "Tolet" },
	magenta: { colorCode: "#FF00FF", color: "magenta", colorDisplay: "Magenta" },
	orchid: { colorCode: "#DA70D6", color: "orchid", colorDisplay: "Orquídea" },
	mediumvioletred: {
		colorCode: "#C71585",
		color: "mediumvioletred",
		colorDisplay: "Vermelho Violeta Médio",
	},
	palevioletred: {
		colorCode: "#DB7093",
		color: "palevioletred",
		colorDisplay: "Vermelho Violeta Pálido",
	},
	deeppink: {
		colorCode: "#FF1493",
		color: "deeppink",
		colorDisplay: "Rosa Pink",
	},
	hotpink: {
		colorCode: "#FF69B4",
		color: "hotpink",
		colorDisplay: "Rosa Quente",
	},
	lightpink: {
		colorCode: "#FFB6C1",
		color: "lightpink",
		colorDisplay: "Luz Rosa",
	},
	pink: { colorCode: "#FFC0CB", color: "pink", colorDisplay: "Rosa" },
	antiquewhite: {
		colorCode: "#FAEBD7",
		color: "antiquewhite",
		colorDisplay: "Branco Antigo",
	},
	beige: { colorCode: "#F5F5DC", color: "beige", colorDisplay: "Bege" },
	bisque: { colorCode: "#FFE4C4", color: "bisque", colorDisplay: "Bisque" },
	blanchedalmond: {
		colorCode: "#FFEBCD",
		color: "blanchedalmond",
		colorDisplay: "Amêndoa Branqueada",
	},
	wheat: { colorCode: "#F5DEB3", color: "wheat", colorDisplay: "Trigo" },
	cornsilk: {
		colorCode: "#FFF8DC",
		color: "cornsilk",
		colorDisplay: "Seda De Milho",
	},
	lemonchiffon: {
		colorCode: "#FFFACD",
		color: "lemonchiffon",
		colorDisplay: "Chiffon De Limão",
	},
	lightgoldenrodyellow: {
		colorCode: "#FAFAD2",
		color: "lightgoldenrodyellow",
		colorDisplay: "Haste Dourada Clara Amarela",
	},
	lightyellow: {
		colorCode: "#FFFFE0",
		color: "lightyellow",
		colorDisplay: "Luz Amarela",
	},
	saddlebrown: {
		colorCode: "#8B4513",
		color: "saddlebrown",
		colorDisplay: "Sela Marrom",
	},
	sienna: { colorCode: "#A0522D", color: "sienna", colorDisplay: "Siena" },
	chocolate: {
		colorCode: "#D2691E",
		color: "chocolate",
		colorDisplay: "Chocolate",
	},
	peru: { colorCode: "#CD853F", color: "peru", colorDisplay: "Peru" },
	sandybrown: {
		colorCode: "#F4A460",
		color: "sandybrown",
		colorDisplay: "Marrom Arenoso",
	},
	burlywood: {
		colorCode: "#DEB887",
		color: "burlywood",
		colorDisplay: "Madeira Robusta",
	},
	tan: { colorCode: "#D2B48C", color: "tan", colorDisplay: "Bronzeado" },
	rosybrown: {
		colorCode: "#BC8F8F",
		color: "rosybrown",
		colorDisplay: "Marrom Rosado",
	},
	moccasin: {
		colorCode: "#FFE4B5",
		color: "moccasin",
		colorDisplay: "Mocassim",
	},
	navajowhite: {
		colorCode: "#FFDEAD",
		color: "navajowhite",
		colorDisplay: "Navajo Branco",
	},
	peachpuff: {
		colorCode: "#FFDAB9",
		color: "peachpuff",
		colorDisplay: "Folhado De Pêssego",
	},
	mistyrose: {
		colorCode: "#FFE4E1",
		color: "mistyrose",
		colorDisplay: "Rosa Enevoada",
	},
	lavenderblush: {
		colorCode: "#FFF0F5",
		color: "lavenderblush",
		colorDisplay: "Rubor De Lavanda",
	},
	linen: { colorCode: "#FAF0E6", color: "linen", colorDisplay: "Linho" },
	oldlace: {
		colorCode: "#FDF5E6",
		color: "oldlace",
		colorDisplay: "Renda Velha",
	},
	papayawhip: {
		colorCode: "#FFEFD5",
		color: "papayawhip",
		colorDisplay: "Chicote De Papaia",
	},
	seashell: {
		colorCode: "#FFF5EE",
		color: "seashell",
		colorDisplay: "Concha Do Mar",
	},
	mintcream: {
		colorCode: "#F5FFFA",
		color: "mintcream",
		colorDisplay: "Creme De Menta",
	},
	slategray: {
		colorCode: "#708090",
		color: "slategray",
		colorDisplay: "Ardósia Cinza",
	},
	lightslategray: {
		colorCode: "#778899",
		color: "lightslategray",
		colorDisplay: "Cinza Ardósia Claro",
	},
	lightsteelblue: {
		colorCode: "#B0C4DE",
		color: "lightsteelblue",
		colorDisplay: "Azul Aço Claro",
	},
	lavender: {
		colorCode: "#E6E6FA",
		color: "lavender",
		colorDisplay: "Lavanda",
	},
	floralwhite: {
		colorCode: "#FFFAF0",
		color: "floralwhite",
		colorDisplay: "Floral Branco",
	},
	aliceblue: {
		colorCode: "#F0F8FF",
		color: "aliceblue",
		colorDisplay: "Alice Azul",
	},
	ghostwhite: {
		colorCode: "#F8F8FF",
		color: "ghostwhite",
		colorDisplay: "Fantasma Branco",
	},
	honeydew: { colorCode: "#F0FFF0", color: "honeydew", colorDisplay: "Melada" },
	ivory: { colorCode: "#FFFFF0", color: "ivory", colorDisplay: "Marfim" },
	azure: { colorCode: "#F0FFFF", color: "azure", colorDisplay: "Azul" },
	snow: { colorCode: "#FFFAFA", color: "snow", colorDisplay: "Neve" },
	black: { colorCode: "#000000", color: "black", colorDisplay: "Preto" },
	dimgray: {
		colorCode: "#696969",
		color: "dimgray",
		colorDisplay: "Cinza Escuro",
	},
	gray: { colorCode: "#808080", color: "gray", colorDisplay: "Cinza" },
	darkgray: {
		colorCode: "#A9A9A9",
		color: "darkgray",
		colorDisplay: "Cinza Escuro",
	},
	silver: { colorCode: "#C0C0C0", color: "silver", colorDisplay: "Prata" },
	lightgray: {
		colorCode: "#D3D3D3",
		color: "lightgray",
		colorDisplay: "Cinza Claro",
	},
	gainsboro: {
		colorCode: "#DCDCDC",
		color: "gainsboro",
		colorDisplay: "Ganhosboro",
	},
	whitesmoke: {
		colorCode: "#F5F5F5",
		color: "whitesmoke",
		colorDisplay: "Fumaça Branca",
	},
	white: { colorCode: "#FFFFFF", color: "white", colorDisplay: "Branco" },
	marsala: { colorCode: "#B57170", color: "marsala", colorDisplay: "Marsala" },
	lilac: { colorCode: "#c8a2c8", color: "lilac", colorDisplay: "Lilás" },
	lighpink: {
		colorCode: "#FFB6C1",
		color: "lighpink",
		colorDisplay: "Rosa Bebê",
	},
}; */

export const searchColor = [
	"marrom",
	"vermelho escuro",
	"castanho",
	"tijolo refratário",
	"carmesim",
	"vermelho",
	"tomate",
	"coral",
	"vermelho indiano",
	"coral claro",
	"salmão escuro",
	"salmão",
	"salmão claro",
	"vermelho alaranjado",
	"laranja escuro",
	"laranja",
	"ouro",
	"haste dourada escura",
	"vara de ouro",
	"haste dourada pálida",
	"cáqui escuro",
	"cáqui",
	"oliva",
	"amarelo",
	"amarelo verde",
	"verde oliva escuro",
	"azeitona monótona",
	"gramado verde",
	"verde amarelo",
	"verde escuro",
	"verde",
	"verde floresta",
	"lima",
	"verde limão",
	"luz verde",
	"verde pálido",
	"verde mar escuro",
	"verde primavera médio",
	"primavera verde",
	"verde mar",
	"aqua marinho médio",
	"verde mar médio",
	"verde mar claro",
	"cinza ardósia escuro",
	"cerceta",
	"ciano escuro",
	"aqua",
	"ciano",
	"ciano claro",
	"turquesa escuro",
	"turquesa",
	"turquesa médio",
	"turquesa pálida",
	"verde água",
	"pó azul",
	"azul bebê",
	"azul cadete",
	"aço azul",
	"flor de milho azul",
	"céu azul profundo",
	"trapaceiro azul",
	"azul claro",
	"céu azul",
	"céu azul claro",
	"azul da meia noite",
	"marinha",
	"azul escuro",
	"azul médio",
	"azul royal",
	"violeta azul",
	"índigo",
	"azul ardósia escuro",
	"azul ardósia",
	"azul ardósia médio",
	"roxo médio",
	"magenta escuro",
	"violeta escuro",
	"orquídea escura",
	"orquídea média",
	"roxo",
	"cardo",
	"ameixa",
	"tolet",
	"magenta",
	"orquídea",
	"vermelho violeta médio",
	"vermelho violeta pálido",
	"rosa pink",
	"rosa quente",
	"luz rosa",
	"rosa",
	"branco antigo",
	"bege",
	"bisque",
	"amêndoa branqueada",
	"trigo",
	"seda de milho",
	"chiffon de limão",
	"haste dourada clara amarela",
	"luz amarela",
	"sela marrom",
	"siena",
	"chocolate",
	"peru",
	"marrom arenoso",
	"madeira robusta",
	"bronzeado",
	"marrom rosado",
	"mocassim",
	"navajo branco",
	"folhado de pêssego",
	"rosa enevoada",
	"rubor de lavanda",
	"linho",
	"renda velha",
	"chicote de papaia",
	"concha do mar",
	"creme de menta",
	"ardósia cinza",
	"cinza ardósia claro",
	"azul aço claro",
	"lavanda",
	"floral branco",
	"alice azul",
	"fantasma branco",
	"melada",
	"marfim",
	"azul",
	"neve",
	"preto",
	"cinza escuro",
	"cinza",
	"cinza escuro médio",
	"prata",
	"cinza claro",
	"ganhosboro",
	"fumaça branca",
	"branco",
	"marsala",
	"lilás",
	"rosa bebê",
];
